export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const MOVIE_SEARCHED_REQUEST = "MOVIE_SEARCHED_REQUEST";
export const MOVIE_SEARCHED_SUCCESS = "MOVIE_SEARCHED_SUCCESS";
export const MOVIE_SEARCHED_FAIL = "MOVIE_SEARCHED_FAIL";

export const MOVIE_INFO_REQUEST = "MOVIE_INFO_REQUEST";
export const MOVIE_INFO_SUCCESS = "MOVIE_INFO_SUCCESS";
export const MOVIE_INFO_FAIL = "MOVIE_INFO_FAIL";
